### ISSUE TITLE
Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)

### ISSUE THREAD

**Issue by bizmate** [rishabh3354/PDF2OCR#1]
I tried installing the app with the standard `sudo snap install pdf2go`
Then I tried installing following the instructions on the application page 

`sudo snap remove pdf2go --purge && sudo snap install pdf2go && sudo snap refresh pdf2go && sudo snap install pyqt5-runtime-lite && sudo snap refresh pyqt5-runtime-lite && pdf2go`

However, in both cases I get the following errors/problems:

1 - when i browse files not all mounted media is accessible, only the hardisk where the home directory is installed is visible. The app has no access to other mounts
2 - The app constantly crashes  with the following error once i select a file , ie 1 open app, 2 browse for a pdf file, 3 select file. 

Below the output in the terminal after installing and trying to open a PDF

```
$  sudo snap remove pdf2go --purge && sudo snap install pdf2go && sudo snap refresh pdf2go && sudo snap install pyqt5-runtime-lite && sudo snap refresh pyqt5-runtime-lite && pdf2go
pdf2go removed
pdf2go 2024.1.2 from WarlordSoft ✅ (rishabh3354) installed
snap "pdf2go" has no available updates
snap "pyqt5-runtime-lite" is already installed, see 'snap help refresh'
snap "pyqt5-runtime-lite" has no available updates
Gtk-Message: 10:41:24.391: Failed to load module "xapp-gtk3-module"
Gtk-Message: 10:41:24.392: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:41:24.392: Failed to load module "canberra-gtk-module"

(python3:20016): Gtk-WARNING **: 10:41:24.412: Theme parsing error: gtk-dark.css:1413:23: 'font-feature-settings' is not a valid property name

(python3:20016): Gtk-WARNING **: 10:41:24.414: Theme parsing error: gtk-dark.css:3286:25: 'font-feature-settings' is not a valid property name

(python3:20016): Gtk-WARNING **: 10:41:24.415: Theme parsing error: gtk-dark.css:3748:23: 'font-feature-settings' is not a valid property name
Gtk-Message: 10:41:24.432: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:41:24.435: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
QApplication: invalid style override passed, ignoring it.
QFont::setPixelSize: Pixel size <= 0 (0)

(python3:20016): GLib-GIO-WARNING **: 10:41:38.146: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
Traceback (most recent call last):
  File "/snap/pdf2go/55/pdf2go.py", line 311, in browse_button_clicked
    self.total_pages = self.get_pdf_total_pages(fileName[0])
  File "/snap/pdf2go/55/pdf2go.py", line 516, in get_pdf_total_pages
    pdf = PdfFileReader(open(path, 'rb'))
  File "/snap/pdf2go/55/lib/python3.6/site-packages/PyPDF2/_reader.py", line 1974, in __init__
    deprecation_with_replacement("PdfFileReader", "PdfReader", "3.0.0")
  File "/snap/pdf2go/55/lib/python3.6/site-packages/PyPDF2/_utils.py", line 369, in deprecation_with_replacement
    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))
  File "/snap/pdf2go/55/lib/python3.6/site-packages/PyPDF2/_utils.py", line 351, in deprecation
    raise DeprecationError(msg)
PyPDF2.errors.DeprecationError: PdfFileReader is deprecated and was removed in PyPDF2 3.0.0. Use PdfReader instead.
Aborted (core dumped)
```

Could you please suggest what to do next?

**Comment by rishabh3354** [comment]
Thanks for reporting it. Let me check

**Comment by rishabh3354** [comment]
issue is fixed. please update your app using cmd below:
sudo snap refresh pdf2go

**Comment by bizmate** [comment]
Trying to update does nothing.

```
$ sudo snap refresh pdf2go
[sudo] password for user: 
snap "pdf2go" has no available updates
```


I had to run the remove and install as noted in the README or it would not refresh.

**Comment by rishabh3354** [comment]
Because your snap package had already updated. That is why it is showing no available updates.
You can use the app and test some images. Issue has been fixed
Thanks
